# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-11T06:55:01+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class BadRequestErrorResponseDto(BaseModel):
    statusCode: Annotated[float, Field(examples=[400])]
    message: Annotated[str, Field(examples=['現在のパスワードが正しくありません'])]
    error: Annotated[str, Field(examples=['Bad Request'])]


class SignupRequestDto(BaseModel):
    email: Annotated[str, Field(examples=['user@example.com'])]


class ValidationErrorResponseDto(BaseModel):
    statusCode: Annotated[float, Field(examples=[400])]
    message: Annotated[
        list[str],
        Field(
            examples=[
                [
                    'email must be an email',
                    'password must be longer than or equal to 8 characters',
                ]
            ]
        ),
    ]
    error: Annotated[str, Field(examples=['Bad Request'])]


class ConflictErrorResponseDto(BaseModel):
    statusCode: Annotated[float, Field(examples=[409])]
    message: Annotated[
        str, Field(examples=['このメールアドレスは既に使用されています'])
    ]
    error: Annotated[str, Field(examples=['Conflict'])]


class InternalServerErrorResponseDto(BaseModel):
    statusCode: Annotated[float, Field(examples=[500])]
    message: Annotated[str, Field(examples=['サーバーエラー'])]
    error: Annotated[str, Field(examples=['Internal Server Error'])]


class VerifyEmailRequestDto(BaseModel):
    token: Annotated[str, Field(description='メールアドレス確認トークン')]


class VerifyEmailResponseDto(BaseModel):
    setupToken: Annotated[str, Field(description='初期設定用ワンタイムトークン')]


class SetupRequestDto(BaseModel):
    setupToken: Annotated[str, Field(examples=['setup-token'])]
    password: Annotated[str, Field(examples=['password123'], min_length=8)]


class LoginResponseDto(BaseModel):
    accessToken: Annotated[
        str, Field(examples=['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'])
    ]


class LoginRequestDto(BaseModel):
    email: Annotated[str, Field(examples=['user@example.com'])]
    password: Annotated[str, Field(examples=['password123'])]


class UnauthorizedErrorResponseDto(BaseModel):
    statusCode: Annotated[float, Field(examples=[401])]
    message: Annotated[
        str, Field(examples=['メールアドレスまたはパスワードが正しくありません'])
    ]
    error: Annotated[str, Field(examples=['Unauthorized'])]


class ForgotPasswordRequestDto(BaseModel):
    email: Annotated[
        str, Field(description='メールアドレス', examples=['user@example.com'])
    ]


class ValidateResetTokenRequestDto(BaseModel):
    token: Annotated[str, Field(description='パスワードリセットトークン')]


class ResetPasswordRequestDto(BaseModel):
    token: Annotated[str, Field(description='パスワードリセットトークン')]
    newPassword: Annotated[
        str,
        Field(description='新しいパスワード（8文字以上）', examples=['NewP@ssw0rd!']),
    ]


class ChangePasswordRequestDto(BaseModel):
    currentPassword: Annotated[str, Field(description='現在のパスワード')]
    newPassword: Annotated[
        str,
        Field(description='新しいパスワード（8文字以上）', examples=['NewP@ssw0rd!']),
    ]


class ExchangeRequestDto(BaseModel):
    redirect: Annotated[
        str,
        Field(
            description='遷移先のコールバック URL',
            examples=['http://localhost:3002/callback'],
        ),
    ]


class ExchangeResponseDto(BaseModel):
    code: Annotated[str, Field(description='認可コード')]


class VerifyExchangeRequestDto(BaseModel):
    code: Annotated[str, Field(description='認可コード')]


class ExchangeUserDto(BaseModel):
    id: Annotated[str, Field(description='ユーザー ID')]
    email: Annotated[str, Field(description='メールアドレス')]
    roles: Annotated[list[str], Field(description='ロール一覧')]


class VerifyExchangeResponseDto(BaseModel):
    accessToken: Annotated[str, Field(description='アクセストークン')]
    user: Annotated[ExchangeUserDto, Field(description='ユーザー情報')]
